# Generated by Django 5.0.2 on 2025-08-05 13:36

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('slug', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('variant', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('singleline_value', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('richtext_value', models.TextField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('code', models.CharField(blank=True, default='', max_length=100)),
                ('value', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('order', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('name', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('option', 'Option')], db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
    ]
