# Generated by Django 5.0.2 on 2025-08-05 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('singleline', 'singleline'), ('textarea', 'textarea'), ('option', 'option')], db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
